apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-portal.fullname" . }}-aws-config
  labels:
    {{- include "user-portal.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.aws.region | quote }}